version: "3.4"

services:
  dashboard:
    image: schulcloud/dashboard
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # JIRA
      - JIRA_URL=${JIRA_URL}
      - JIRA_USERNAME=${JIRA_USERNAME}
      - JIRA_PASSWORD=${JIRA_PASSWORD}
    ports:
      - 8080:8080
